---
title: Shakespearean insult generator
hero_image: images/banner.png
description: In this resource you will write a Python script to generate insults,
  Elizabethan-style.
original_url: https://raspberrypi.org/learning/shakespearean-insult-generator
theme: red
duration: 2
ingredient: false
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: literature
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
listed: false
copyedit: false
last_tested: "2026-01-23"
steps:
- title: Step 1
- title: Step 2
  completion:
  - engaged
- title: Step 3
- title: Step 4
- title: Step 5
- title: Step 6
  completion:
  - internal
  - external